name: python mlops
on:
  push:
    branches: [chap2]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          make install
      - name: Lint
        run: |
          make lint
      - name: test
        run: |
          make test
      - name: Set up gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      # Deploy to CloudRun
      - name: Deploy to CloudRun
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --image "eu.gcr.io/my-container-project/$SERVICE_NAME:$GITHUB_SHA" \
            --region "$RUN_REGION" \
            --platform "managed" \
            --allow-unauthenticated \
            --memory=512Mi
