name: python mlops
on:
  push:
    branches: [chap2]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          make install
      - name: Lint
        run: |
          make lint
      - name: test
        run: |
          make test
      - name: start
        run: |
          make start
