name: python mlops
on:
  push:
    branches: [chap2]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          make install
      - name: Lint
        run: |
          make lint
      - name: test
        run: |
          make test
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        # Deploy to CloudRun
      - name: Deploy to CloudRun
        run: |-
          gcloud run deploy flask-ml \
            --quiet \
            --image "gcr.io/mlops_test/flask-ml:$GITHUB_SHA" \
            --region us-central1 \
            --platform "managed" \
            --allow-unauthenticated \
            --memory=512Mi
